sudo: required
version: '2.7'
services:
- docker
language: java
node_js:
- stable
git:
  quiet: true
branches:
  only:
  - master
script:
# Enter Scripts Here
- cd backend/
notifications:
  email: false